import { FunctionSquare } from 'lucide-react'
import type { TransformationStep } from '@/crypto/types/CipherAlgorithm'

interface MathViewProps {
  step: TransformationStep | null
}

/**
 * SHOW MATHEMATICS view.
 * Renders the per-character arithmetic chain generated by the engine.
 */
export function MathView({ step }: MathViewProps) {
  if (!step || step.status === 'skipped') {
    return (
      <div className="flex items-center gap-2 text-xs text-[var(--c-text-faint)]">
        <FunctionSquare size={14} className="text-[var(--c-text-faint)]" />
        {step ? 'No arithmetic for a non-alphabetic character.' : 'Select a character to see its mathematics.'}
      </div>
    )
  }

  return (
    <div className="space-y-2">
      {step.mathematics.map((line, i) => (
        <div
          key={i}
          className="flex items-center gap-3 rounded-md border border-[var(--c-border)] bg-[rgba(0,0,0,0.2)] px-3 py-2 font-mono text-sm"
        >
          <span className="mono-label !text-[0.5rem] text-[var(--c-text-faint)]">{i + 1}</span>
          <span className={i === step.mathematics.length - 1 ? 'font-semibold text-[rgb(var(--c-core))]' : 'text-[var(--c-text)]'}>
            {line}
          </span>
        </div>
      ))}
    </div>
  )
}
