import type { CipherMetadata } from './CryptoTypes'

/**
 * A cipher's key is algorithm-specific:
 *  - Caesar / Affine use a numeric shift -> `number`
 *  - Vigenère / Playfair use a keyword       -> `string`
 *  - Atbash / Rail Fence may be keyless       -> represented as 0 / ''
 */
export type CipherKey = number | string

/** How the UI should collect the key for this cipher. */
export type KeyType = 'shift' | 'string' | 'none'

/** The per-character status inside a transformation. */
export type StepStatus = 'transformed' | 'skipped'

/** Whether the step is running encryption or decryption. */
export type StepMode = 'encrypt' | 'decrypt'

/**
 * One character's full transformation record.
 * This is what powers every educational visualization (inspector, mathematics,
 * step-by-step). Generated by the engine — never hardcoded.
 */
export interface TransformationStep {
  /** Index of the character within the original string. */
  index: number
  /** The original character (case preserved). */
  originalCharacter: string
  /** Alphabet value 0–25 (A=0). null for non-alphabetic characters. */
  originalValue: number | null
  /** The applied (normalized) key/shift. null for non-alphabetic characters. */
  shift: number | null
  /** Human-readable arithmetic, e.g. "(7 + 3) mod 26". null when skipped. */
  calculation: string | null
  /** Result alphabet value 0–25. null when skipped. */
  resultValue: number | null
  /** Result character (case preserved). null when skipped. */
  resultCharacter: string | null
  status: StepStatus
  mode: StepMode
  /** Short reason shown for skipped characters, e.g. "NON-ALPHABETIC". */
  reason?: string
  /** Optional educational note for the inspector (e.g. substitution rule). */
  note?: string
  /** Ordered math chain for "SHOW MATHEMATICS". Empty when skipped. */
  mathematics: string[]
}

/** Data the visualization layer can request from a cipher. */
export interface CipherVisualization {
  /** The alphabet A–Z. */
  alphabet: string[]
  /** The alphabet rotated by the current key (plain → cipher). */
  cipherAlphabet: string[]
}

/**
 * Common contract every cipher in CRYPTOLAB implements.
 * Keeps the mathematical logic out of React and lets future algorithms
 * (Atbash, Vigenère, Playfair, …) slot in behind the same interface.
 */
export interface CipherAlgorithm {
  meta: CipherMetadata
  keyType: KeyType
  encrypt(text: string, key: CipherKey): string
  decrypt(text: string, key: CipherKey): string
  getSteps(text: string, key: CipherKey, mode?: StepMode): TransformationStep[]
  getVisualizationData(key: CipherKey): CipherVisualization
}
